# Generated by Django 5.2.5 on 2025-09-18 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='spots/images/'),
        ),
        migrations.AddField(
            model_name='spot',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='spot',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
