# Generated by Django 5.2.3 on 2025-10-22 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0004_advisoryarticle_casestudy_advisorysession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(choices=[('JOUR', 'Jour'), ('SEMAINE', 'Semaine'), ('MOIS', 'Mois'), ('HEURE', 'Heure'), ('MINUTE', 'Minute'), ('SPOT', 'Spot'), ('FORFAIT', 'Forfait')], max_length=20)),
                ('unit_quantity', models.PositiveIntegerField(default=1)),
                ('min_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('max_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_timeslot', models.BooleanField(default=False)),
                ('timeslot_notes', models.CharField(blank=True, max_length=200)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_quote_only', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='spot.servicecategory')),
            ],
        ),
    ]
