# Generated by Django 5.2.3 on 2025-10-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0005_servicecategory_serviceitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'ordering': ['category__order', 'name']},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_prime',
            field=models.BooleanField(default=False),
        ),
    ]
