# Generated by Django 5.2.5 on 2025-10-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0006_alter_servicecategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
