# Generated by Django 5.2.5 on 2025-10-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0007_remove_payment_campaign_delete_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('spot_upload', 'Je fournis mon spot'), ('spot_creation', "Je demande la création d'un spot")], default='spot_upload', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='key_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='requested_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
