# Generated by Django 5.2.5 on 2025-10-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0008_campaign_campaign_type_campaign_key_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.CharField(blank=True, choices=[('tv', 'Télévision'), ('urban', 'Écran urbain'), ('online', 'En ligne')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='objective',
            field=models.CharField(blank=True, choices=[('notoriete', 'Notoriété'), ('promotion', 'Promotion'), ('sensibilisation', 'Sensibilisation')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='preferred_time_slots',
            field=models.ManyToManyField(blank=True, related_name='preferred_in_campaigns', to='spot.timeslot'),
        ),
    ]
