# Generated by Django 5.2.3 on 2025-11-06 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0009_campaign_channel_campaign_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spot.contactrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spot.correspondencethread'),
        ),
    ]
