# Generated by Django 5.2.5 on 2025-11-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0010_notification_related_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='message_defilant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
