# Generated by Django 5.2.5 on 2025-11-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0011_campaign_message_defilant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='message_defilant',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spot.spot'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur'), ('journaliste', 'Journaliste'), ('diffuseur', 'Diffuseur')], default='client', max_length=15),
        ),
    ]
