# Generated by Django 5.2.5 on 2025-11-27 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0013_notification_related_spot_playlist_playlistitem_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlistschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistschedule',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='spot',
        ),
        migrations.RemoveField(
            model_name='playlistschedule',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='campaignhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Créée'), ('updated', 'Modifiée'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('payment_made', 'Paiement effectué'), ('spot_uploaded', 'Spot téléchargé'), ('spot_approved', 'Spot approuvé'), ('broadcasted', 'Diffusé'), ('spot_downloaded', 'Spot téléchargé par diffuseur'), ('spot_received', 'Réception du spot confirmée')], max_length=30),
        ),
        migrations.AlterField(
            model_name='campaignhistory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur'), ('diffuseur', 'Diffuseur')], default='client', max_length=10),
        ),
        migrations.CreateModel(
            name='SpotReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step1_confirmed', models.BooleanField(default=False)),
                ('step2_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='spot.spot')),
            ],
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistItem',
        ),
        migrations.DeleteModel(
            name='PlaylistSchedule',
        ),
    ]
