# Generated by Django 5.2.5 on 2025-11-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0014_remove_playlistitem_playlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Créée'), ('updated', 'Modifiée'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('payment_made', 'Paiement effectué'), ('spot_uploaded', 'Spot téléchargé'), ('spot_approved', 'Spot approuvé'), ('broadcasted', 'Diffusé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignhistory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur'), ('broadcaster', 'Diffuseur')], default='client', max_length=12),
        ),
        migrations.DeleteModel(
            name='SpotReceipt',
        ),
    ]
