# Generated by Django 5.2.5 on 2025-12-05 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0015_alter_campaignhistory_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur'), ('diffuser', 'Diffuseur')], default='client', max_length=10),
        ),
        migrations.CreateModel(
            name='CoverageRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('press_conference', 'Conférence de presse'), ('seminar_workshop', 'Séminaire / Atelier'), ('inauguration', 'Inauguration'), ('public_event', 'Manifestation publique'), ('government_activity', 'Activité gouvernementale'), ('product_launch', 'Lancement de produit'), ('interviews', 'Interviews'), ('cultural_sport', 'Événement culturel / sportif'), ('other', 'Autre')], max_length=50)),
                ('event_type_other', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('meeting_point', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('other_contacts', models.TextField(blank=True)),
                ('coverage_type', models.CharField(choices=[('video_report', 'Reportage vidéo'), ('photo_report', 'Reportage photo'), ('interview', 'Interview'), ('voiceover_micro', 'Voix off / Micro-trottoir'), ('live', 'Direct / Live'), ('web_article', 'Article web'), ('mix_video_interview', 'Mix vidéo + interview'), ('editorial_defined', 'À définir par la rédaction')], max_length=50)),
                ('coverage_objective', models.TextField(blank=True)),
                ('urgency_level', models.CharField(choices=[('normal', 'Normal'), ('priority', 'Prioritaire'), ('urgent_24h', 'Urgent (dans les 24h)')], default='normal', max_length=20)),
                ('response_deadline', models.DateField(blank=True, null=True)),
                ('confirm_info', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('review', 'En révision'), ('scheduled', 'Planifié'), ('closed', 'Clôturé')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='coverage_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='spot.coveragerequest')),
            ],
        ),
    ]
