# Generated by Django 5.2.5 on 2025-12-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0016_alter_user_role_coveragerequest_coverageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spot.coveragerequest'),
        ),
    ]
