# Generated by Django 5.2.5 on 2025-12-09 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0017_notification_related_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('on_mission', 'En mission'), ('resting', 'En repos'), ('offline', 'Hors ligne')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='journalists/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('on_mission', 'En mission'), ('resting', 'En repos'), ('offline', 'Hors ligne')], default='available', max_length=20)),
                ('specialties', models.TextField(blank=True)),
                ('workload_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur'), ('diffuser', 'Diffuseur'), ('editorial_manager', 'Responsable Rédaction')], default='client', max_length=20),
        ),
        migrations.CreateModel(
            name='CoverageAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigné'), ('in_field', 'Sur le terrain'), ('delivered', 'Contenu livré'), ('done', 'Terminé')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='spot.coveragerequest')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spot.driver')),
                ('journalist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spot.journalist')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='spot.coverageassignment')),
            ],
        ),
    ]
