# Generated by Django 5.2.5 on 2025-12-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0019_editorial_permissions_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='coverage_zones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_available',
            field=models.BooleanField(default=False),
        ),
    ]
