# Generated by Django 5.2.5 on 2025-12-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0020_driver_coverage_zones_driver_license_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='coverage_zones',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='license_type',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_available',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
