# Generated by Django 5.2.5 on 2025-12-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0021_remove_driver_coverage_zones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_status',
            field=models.CharField(blank=True, help_text='État du véhicule attribué (ex: Bon état, En maintenance)', max_length=100),
        ),
    ]
