# Generated by Django 5.2.5 on 2025-12-23 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0022_remove_notification_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentNotificationCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_kind', models.CharField(choices=[('journalist', 'Journaliste'), ('driver', 'Chauffeur')], max_length=20)),
                ('to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('to_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('confirm_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('confirmed', 'Confirmée'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='active', max_length=20)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_via', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_campaigns', to='spot.coverageassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentNotificationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('web', 'Web')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'En file'), ('sent', 'Envoyé'), ('delivered', 'Délivré'), ('failed', 'Échec'), ('skipped', 'Ignoré'), ('confirmed', 'Confirmé')], default='queued', max_length=20)),
                ('to', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('error', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='spot.assignmentnotificationcampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
