# Generated by Django 5.2.5 on 2026-01-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0024_recreate_assignment_notification_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos/'),
        ),
    ]
