"""
Django settings for spot_bf1 project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-*k-w)*v4nnxe=yyrf58j@f(k8r$+oc8_h%$#3w&)7yz4z^%faf',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', '1').strip().lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '*').split(',') if h]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'channels',
    'spot',
    'crispy_forms',
    'crispy_tailwind',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'spot.middleware.DiffusionStatusValidationMiddleware',
    'spot.middleware.AdminRestrictionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spot_bf1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'spot.context_processors.widget_config',
                'spot.context_processors.chatbot_config',
                'spot.context_processors.notifications_summary',
            ],
        },
    },
]

WSGI_APPLICATION = 'spot_bf1.wsgi.application'
ASGI_APPLICATION = 'spot_bf1.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DATABASE_NAME', 'gestion_publicitaire'),
        'USER': os.environ.get('DATABASE_USER', 'spot_bf1'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', '1234Nana'),
        'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
        'PORT': os.environ.get('DATABASE_PORT', '5433'),
    }
}

if os.environ.get('DJANGO_USE_SQLITE') == '1':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Email settings (for development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Logging configuration
from .logging_config import LOGGING

# Custom User Model
AUTH_USER_MODEL = 'spot.User'

# Feature flags
ENABLE_PAYMENTS = False

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# WhatsApp Chat Widget configuration
# Use E.164 format for phone (e.g., '+22670123456')
WHATSAPP_PHONE = '+22674470032'
WHATSAPP_DEFAULT_MESSAGE = 'Bonjour BF1 TV, je souhaite échanger avec votre équipe.'
WHATSAPP_WIDGET_ENABLED = True
WHATSAPP_WIDGET_POSITION = 'bottom-right'  # options: bottom-right, bottom-left
WHATSAPP_WIDGET_COLOR = '#25D366'  # WhatsApp green
WHATSAPP_WIDGET_SIZE = 'md'  # options: sm, md, lg

# Chatbot configuration (local provider)
CHATBOT_ENABLED = True
CHATBOT_PROVIDER = 'local'
# Mode d'escalade demandé: 'contact' (renvoie vers la page /contact/)
CHATBOT_ESCLATE_MODE = 'contact'
CHATBOT_DEFAULT_SUGGESTIONS = [
    'Créer une campagne',
    'Téléverser un spot',
    'Planifier une diffusion',
    'Voir le calendrier',
    'Demande de couverture',
    'Suivre mes échanges',
    'Contacter le support',
    'Orientation',
    'Bilan / rapports',
]

# Advanced local LLM options (offline, no external service)
# Path to a local GGUF/GGML model file (e.g., phi-3-mini, mistral-instruct)
CHATBOT_MODEL_PATH = os.environ.get('CHATBOT_MODEL_PATH', '')
# Max conversational turns stored in session for context
CHATBOT_MAX_CONTEXT = int(os.environ.get('CHATBOT_MAX_CONTEXT', '8'))
# Optional local knowledge base directory with .txt/.md files
CHATBOT_KNOWLEDGE_DIR = os.environ.get('CHATBOT_KNOWLEDGE_DIR', os.path.join(BASE_DIR, 'media', 'chatbot_kb'))
# Enable lightweight on-disk memory (JSONL) for continuous learning
CHATBOT_ENABLE_PERSISTENT_MEMORY = bool(int(os.environ.get('CHATBOT_ENABLE_PERSISTENT_MEMORY', '1')))
CHATBOT_MEMORY_PATH = os.environ.get('CHATBOT_MEMORY_PATH', os.path.join(BASE_DIR, 'media', 'chatbot_memory.jsonl'))

# Channels (dev: mémoire; prod: Redis via env REDIS_URL si channels_redis est installé)
_redis_url = os.environ.get('REDIS_URL', '').strip()
_has_channels_redis = False
try:
    import channels_redis  # noqa: F401
    _has_channels_redis = True
except Exception:
    _has_channels_redis = False

if _redis_url and _has_channels_redis:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_redis_url]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}
    }
